# Generated by Django 5.2.14 on 2026-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("web_development", "Web Development"),
                            ("python_programming", "Python Programming"),
                            ("data_science", "Data Science"),
                            ("machine_learning", "Machine Learning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
